// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NP.DAL.Context;

#nullable disable

namespace NP.DAL.Migrations
{
    [DbContext(typeof(NPDB))]
    [Migration("20230803023735_EFRepository")]
    partial class EFRepository
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("NP.DAL.Entityes.BreakDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualPaperMoisture")
                        .HasColumnType("REAL");

                    b.Property<double>("ActualPaperWeight")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("EndBreak")
                        .HasColumnType("TEXT");

                    b.Property<double>("ReleerSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("SetpointPaperMoisture")
                        .HasColumnType("REAL");

                    b.Property<double>("SetpointPaperWeight")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("StartBreak")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("TimeBreak")
                        .HasColumnType("TEXT");

                    b.Property<double>("WireSpeed")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("BreaksTable");
                });

            modelBuilder.Entity("NP.DAL.Entityes.СhangeSettingsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SetpointPaperFormatChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("SetpointPaperWeightChange")
                        .HasColumnType("REAL");

                    b.Property<double?>("SetpointWireChange")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("TimeRun")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("СhangeSettingsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
